name: Build MacroQuest Live

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call_build:
    uses: ./.github/workflows/build_shared.yaml
    with:
      client_target: live
    secrets: inherit